# Menu
navs:
    - name: home
      link: /
    - name: archives
      link: /archives
    - name: categories
      link: /categories
    - name: tags
      link: /tags

# Renderer
node_sass:
    outputStyle: nested
    precision: 5
    sourceComments: false
    sourceMap: true
    sourceMapContents: true
    sourceMapEmbed: true
    includePaths:
        - node_modules
